Updated pipeline.yaml

diff --git a/pipeline.yaml b/pipeline.yaml
--- a/pipeline.yaml
+++ b/pipeline.yaml
@@ -125,15 +125,36 @@ stages:
           aws eks update-kubeconfig --region us-east-2 --name cluster-eks
           
           if kubectl rollout status deploy app-sumatoria -n dev --timeout=60s; then
-             echo "Deployment succeeded"
+            echo "Deployment succeeded"
              
           else
-             echo "Deployment failed"
-             echo "\n\n\n --- LOGS:"
-             for i in $(kubectl get pods -l app=app-sumatoria -n dev | grep -e '0/1' | cut -d' ' -f1); do kubectl logs $i -n dev; done
-             echo "\n\n\n --- DESCRIBE POD:"
-             for i in $(kubectl get pods -l app=app-sumatoria -n dev | grep -e '0/1' | cut -d' ' -f1); do kubectl describe pod $i -n dev; done
-             kubectl set image deploy app-sumatoria app-sumatoria=$(previousImage) -n dev
-             exit 1
+            echo "Deployment failed"
+            echo " .----------------.  .----------------.  .----------------.  .----------------."
+            echo "| .--------------. || .--------------. || .--------------. || .--------------. |"
+            echo "| |   _____      | || |     ____     | || |    ______    | || |    _______   | |"
+            echo "| |  |_   _|     | || |   .'    `.   | || |  .' ___  |   | || |   /  ___  |  | |"
+            echo "| |    | |       | || |  /  .--.  \  | || | / .'   \_|   | || |  |  (__ \_|  | |"
+            echo "| |    | |   _   | || |  | |    | |  | || | | |    ____  | || |   '.___`-.   | |"
+            echo "| |   _| |__/ |  | || |  \  `--'  /  | || | \ `.___]  _| | || |  |`\____) |  | |"
+            echo "| |  |________|  | || |   `.____.'   | || |  `._____.'   | || |  |_______.'  | |"
+            echo "| |              | || |              | || |              | || |              | |"
+            echo "| '--------------' || '--------------' || '--------------' || '--------------' |"
+            echo " '----------------'  '----------------'  '----------------'  '----------------'"
+            for i in $(kubectl get pods -l app=app-sumatoria -n dev | grep -e '0/1' | cut -d' ' -f1); do kubectl logs $i -n dev; done
+
+            echo " .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------."
+            echo "| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |"
+            echo "| |  ________    | || |  _________   | || |    _______   | || |     ______   | || |  _______     | || |     _____    | || |   ______     | || |  _________   | |"
+            echo "| | |_   ___ `.  | || | |_   ___  |  | || |   /  ___  |  | || |   .' ___  |  | || | |_   __ \    | || |    |_   _|   | || |  |_   _ \    | || | |_   ___  |  | |"
+            echo "| |   | |   `. \ | || |   | |_  \_|  | || |  |  (__ \_|  | || |  / .'   \_|  | || |   | |__) |   | || |      | |     | || |    | |_) |   | || |   | |_  \_|  | |"
+            echo "| |   | |    | | | || |   |  _|  _   | || |   '.___`-.   | || |  | |         | || |   |  __ /    | || |      | |     | || |    |  __'.   | || |   |  _|  _   | |"
+            echo "| |  _| |___.' / | || |  _| |___/ |  | || |  |`\____) |  | || |  \ `.___.'\  | || |  _| |  \ \_  | || |     _| |_    | || |   _| |__) |  | || |  _| |___/ |  | |"
+            echo "| | |________.'  | || | |_________|  | || |  |_______.'  | || |   `._____.'  | || | |____| |___| | || |    |_____|   | || |  |_______/   | || | |_________|  | |"
+            echo "| |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |"
+            echo "| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |"
+            echo " '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'"
+            for i in $(kubectl get pods -l app=app-sumatoria -n dev | grep -e '0/1' | cut -d' ' -f1); do kubectl describe pod $i -n dev; done
+            kubectl set image deploy app-sumatoria app-sumatoria=$(previousImage) -n dev
+            exit 1
           fi
       #continueOnError: true
